#!/bin/sh

percent=$(acpi | awk '{print $4}' | tr -d "%" | tr -d ",")
status=$(acpi | awk '{print $3}')

if [ "$percent" -gt "60" ]; then
    icon=""
elif [ "$percent" -lt "20" ]; then
    icon=""
else
    icon=""
fi

if [ "$status" == "Charging," ]; then
     icon=""
fi

echo "$icon $percent%"
